spring.application.name=campushire-backend
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/campushire_db
spring.datasource.username=campushire_user
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Security Secrets
jwt.secret=c2VjdXJlX2p3dF9zZWNyZXRfa2V5X2NhbXB1c2hpcmVfcHJvXzIwMjY=
jwt.expirationMs=86400000

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vaidehipatil25002@gmail.com
spring.mail.password=iuqguzvsigowenlo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true